#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP_DIR="${TMPDIR:-/tmp}"
REPORT_PATH="${REPORT_PATH:-$TMP_DIR/phase31-acceptance-evidence.md}"
LOG_DIR="${LOG_DIR:-$TMP_DIR/phase31-acceptance-evidence-logs}"
LOG_TAIL_LINES="${LOG_TAIL_LINES:-80}"
JAVA21_HOME="${JAVA21_HOME:-/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home}"

export JAVA21_HOME

mkdir -p "$LOG_DIR"
mkdir -p "$(dirname "$REPORT_PATH")"

FAILED=0
RESULT_ROWS=()
LOG_SECTIONS=()

redact_log() {
  sed -E \
    -e 's/(Authorization: Bearer )[A-Za-z0-9._~+\/=-]+/\1token:redacted/g' \
    -e 's/("accessToken"[[:space:]]*:[[:space:]]*")[^"]+/\1token:redacted/g' \
    -e 's/(accessToken=)[^[:space:]]+/\1token:redacted/g' \
    -e 's/(AI_CHAT_API_KEY=)[^[:space:]]+/\1value:redacted/g' \
    -e 's/(AI_EMBEDDING_API_KEY=)[^[:space:]]+/\1value:redacted/g' \
    -e 's/(APP_DATASOURCE_PASSWORD=)[^[:space:]]+/\1value:redacted/g' \
    -e 's/sk-[A-Za-z0-9_-]{16,}/sk-redacted/g'
}

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-//; s/-$//'
}

run_check() {
  local name="$1"
  shift
  local slug
  slug="$(slugify "$name")"
  local raw_log="$LOG_DIR/$slug.raw.log"
  local safe_log="$LOG_DIR/$slug.log"
  local status

  set +e
  (
    cd "$ROOT_DIR"
    "$@"
  ) >"$raw_log" 2>&1
  status=$?
  set -e

  redact_log <"$raw_log" >"$safe_log"
  rm -f "$raw_log"

  if [[ "$status" == "0" ]]; then
    RESULT_ROWS+=("| $name | PASS | \`$safe_log\` |")
  else
    RESULT_ROWS+=("| $name | FAIL($status) | \`$safe_log\` |")
    FAILED=1
  fi
  LOG_SECTIONS+=("$name::$safe_log")
}

write_report() {
  {
    printf '# V1 Acceptance Evidence Snapshot\n\n'
    printf 'Generated at: `%s`\n\n' "$(date '+%Y-%m-%d %H:%M:%S %z')"
    printf 'Worktree: `%s`\n\n' "$(cd "$ROOT_DIR" && git branch --show-current 2>/dev/null || printf 'unknown')"
    printf 'Commit: `%s`\n\n' "$(cd "$ROOT_DIR" && git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
    printf 'Secret handling sentinel: `token:redacted`\n\n'
    printf 'This report is generated by `tools/smoke/phase31-acceptance-evidence.sh`. Logs are sanitized by `redact_log` before being referenced here.\n\n'
    printf '## Checks\n\n'
    printf '| Check | Status | Sanitized Log |\n'
    printf '| --- | --- | --- |\n'
    for row in "${RESULT_ROWS[@]}"; do
      printf '%s\n' "$row"
    done
    printf '\n## Log Excerpts\n\n'
    for section in "${LOG_SECTIONS[@]}"; do
      local name="${section%%::*}"
      local log_path="${section#*::}"
      printf '### %s\n\n' "$name"
      printf '```text\n'
      tail -n "$LOG_TAIL_LINES" "$log_path" || true
      printf '\n```\n\n'
    done
  } >"$REPORT_PATH"
}

printf 'phase31AcceptanceEvidence start token:redacted\n'

run_check "Backend smoke" bash -lc 'tools/smoke/phase7-backend-smoke.sh'
run_check "Frontend dev smoke" bash -lc 'tools/smoke/phase30-frontend-dev-smoke.sh'
run_check "Frontend tests" bash -lc 'cd frontend && npm run test'
run_check "Frontend build" bash -lc 'cd frontend && npm run build'
run_check "Backend documentation coverage" bash -lc 'if [[ -x "$JAVA21_HOME/bin/java" ]]; then export JAVA_HOME="$JAVA21_HOME"; export PATH="$JAVA_HOME/bin:$PATH"; fi; cd backend && mvn -Dtest=DocumentationCoverageTest test'

write_report

printf 'phase31AcceptanceEvidence report %s\n' "$REPORT_PATH"
printf 'phase31AcceptanceEvidence complete token:redacted\n'

if [[ "$FAILED" != "0" ]]; then
  exit 1
fi
