CREATE TABLE kb_category (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    parent_id NUMBER(19),
    sort_order NUMBER(10) DEFAULT 0 NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_kb_category_name UNIQUE (name),
    CONSTRAINT ck_kb_category_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT fk_kb_category_parent FOREIGN KEY (parent_id) REFERENCES kb_category(id)
);

CREATE TABLE kb_document (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    category_id NUMBER(19),
    file_name VARCHAR2(255),
    storage_name VARCHAR2(255),
    file_type VARCHAR2(32) DEFAULT 'TEXT' NOT NULL,
    file_size NUMBER(19) DEFAULT 0 NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    parse_status VARCHAR2(32) DEFAULT 'PENDING_PARSE' NOT NULL,
    parse_error VARCHAR2(1000),
    retry_count NUMBER(10) DEFAULT 0 NOT NULL,
    uploaded_by NUMBER(19),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_kb_document_category FOREIGN KEY (category_id) REFERENCES kb_category(id),
    CONSTRAINT fk_kb_document_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES sys_user(id),
    CONSTRAINT ck_kb_document_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_kb_document_deleted CHECK (deleted IN (0, 1)),
    CONSTRAINT ck_kb_document_parse_status CHECK (parse_status IN ('PENDING_PARSE', 'PARSING', 'PARSE_SUCCESS', 'PARSE_FAILED'))
);

CREATE TABLE kb_chunk (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id NUMBER(19) NOT NULL,
    category_id NUMBER(19),
    chunk_index NUMBER(10) NOT NULL,
    content CLOB NOT NULL,
    content_hash VARCHAR2(64) NOT NULL,
    source_title VARCHAR2(200) NOT NULL,
    source_page NUMBER(10),
    embedding VECTOR(1024, FLOAT32) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_kb_chunk_document FOREIGN KEY (document_id) REFERENCES kb_document(id),
    CONSTRAINT fk_kb_chunk_category FOREIGN KEY (category_id) REFERENCES kb_category(id),
    CONSTRAINT ck_kb_chunk_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT uk_kb_chunk_document_index UNIQUE (document_id, chunk_index)
);

CREATE INDEX idx_kb_document_status ON kb_document (parse_status, enabled, deleted);
CREATE INDEX idx_kb_document_category ON kb_document (category_id);
CREATE INDEX idx_kb_chunk_document ON kb_chunk (document_id);
CREATE INDEX idx_kb_chunk_category ON kb_chunk (category_id);
CREATE INDEX idx_kb_chunk_enabled ON kb_chunk (enabled);
CREATE INDEX idx_kb_chunk_hash ON kb_chunk (content_hash);

INSERT INTO kb_category (id, name, sort_order, enabled) VALUES (1, '默认分类', 1, 1);
